### ISSUE TITLE
Publish on `npm` properly?

### ISSUE THREAD

**Issue by gvilarino** [satismeter/satismeter-js#1]
`npm i -D satismeter/satismeter-js`

yeilds 

`"satismeter-js": "satismeter/satismeter-js",` in `package.json`

Expected behavior is be:
`"satismeter-js": "^x.y.z",`

I really fail to understand why you aren't using the standard `npm` approach, which makes it impossible to pin a version.

Same with https://github.com/satismeter/nps-widget

Can you please publish under `satismeter-js` or `satismeter-client-js`?

**Comment by jsedlacek** [comment]
Hi @gvilarino,

The satismeter-js is an experimental library, it's not ready for production use.

Would it work for you if we prepare npm package for the satismeter snippet that can be used like this?

``` js
var satismeter = require('satismeter-snippet');

satismeter({
  writeKey: 'ABC',
  userId: '123',
  traits: {
    name: 'James Hetfield',
    /* ... */
  }
});
```

(This will work the same way as if you used the `HTML snippet` installation method.)

**Comment by jsedlacek** [comment]
@gvilarino We published https://github.com/satismeter/satismeter-loader as a standard way to install satismeter using npm (browserify or webpack).

I am closing this, as the`satismeter-js` package is intended for internal use and it does not make much sense to be published on npm.

**Comment by gvilarino** [comment]
Great, thanks. Will try that out and get back 2 u

**Comment by nicoecheza** [comment]
I don't think injecting a script tag loading the satismeter.js file is the best fix we could make.
The problem with the current satismeter.js file (among the not published to npm one) is that it's failing to transpile with babel (we are currently using webpack). 
If we could just make it transpile without errors, we should be fine.

**Comment by jsedlacek** [comment]
@nicoecheza @gvilarino the async script tag is used on purpose, so that SatisMeter does not slow down your app and is loaded only after your app is initialized.

Why do you think this approach is not right? We could potentially create an npm module containing all the transpiled code, but I don't see any upsides to that approach.

Thanks for clarifying.

**Comment by nicoecheza** [comment]
Yeahp, I think the npm module with transpiled code is a better approach. 
I don't want users to download the script on-demand. And also loading it after my app has initialized won't work on every case (Reference Errors could show up when trying to call the module before it's even loaded).

Regards!

**Comment by gvilarino** [comment]
Besides, the standard approach in any and all `npm` modules is for them to be self-contained or declare dependencies as other `npm` modules. Manually hardcoding a file (that is subject to change, and is downloaded at runtime) makes no sense, it makes an app entirely unreliable and does not comply with the community standards.

What you should do is publish the other script as a separate `npm` module, provide sensible versioning for both on them, and release.

It doesn't matter if it's not prod-ready; that's up to the users and you can just put a disclaimer under `README.md`.

It also doesn't matter that you intend your lib to be client-side only; `node` users may want to toy with this as well.

If you want to make this available from a simple `script` tag you will have to provide a public `CDN` endpoint like `jQuery` or `page.js` do; but providing an `npm`-based delivery is sort-of mandatory.

**Comment by jsedlacek** [comment]
@gvilarino @nicoecheza thanks for your comments.

We understand the power of `npm` for distribution of libraries - we are using it internally as well. However for services like `satismeter` this is not the best model. We are making changes in a fast pace, some of them are not backwards-compatible. It's very convenient for us to have everybody on the latest version.

Most of other services like [intercom](https://docs.intercom.com/install-on-your-product-or-site/quick-install/install-intercom-on-your-web-app), [segment](https://segment.com/docs/sources/website/analytics.js/quickstart/) are using exactly the same approach. I think you are already using these at Mural. Why would you like to use different approach for satismeter?

**Comment by gvilarino** [comment]
thanks for answering! Actually, a good question. The thing is we bundle our web client into a single application and we release it as a single js file. This bundle is built on our CI pipeline and relies entirely on `npm` modules. In order for us to stay on the latest versions we we just declare a loosely pinned versions on our `package.json` and also rely on `greenkeeper` to staying up to date. For breaking changes you can just release a new semver major and it's ok. But if you rely on fetching the JS with as a runtime dependency and that becomes breaking, then you're compromising the whole web app, bypassing all of our CI checks and human testing.

I really understand your need of keeping users up to date, but the fact that this proposed approach may (and does) bring crashing bugs to our prod env is sort of serious; we need to be able to check in advance on our testing envs and have the dependency as a build-time thing.

**Comment by jsedlacek** [comment]
@gvilarino Thanks for explanation. I understand you'd like to have better control of what you release. It's completely reasonable.

Let us evaluate what it takes to release the code whole package to npm. I will get back to you as we progress with it.
