### ISSUE TITLE
Babel es2015 preset

### ISSUE THREAD

**Issue by nicoecheza** [satismeter/satismeter-js#2]
Hi guys, 
We recently removed from our dependencies the babel preset `es2015` in order to replace it for `https://github.com/babel/babel/tree/master/packages/babel-preset-latest`. 
Since that change, our builds stopped working since `satismeter` is not specifying the `es2015` preset on it's `package.json` file.

Anyway you think we can fix this?

I leave the error here so you can see it:
`Couldn't find preset "es2015" relative to directory "/.../node_modules/satismeter-js" while parsing file: /.../node_modules/satismeter-js/index.js`

Thanks!

**Comment by jsedlacek** [comment]
fixed in version 1.1
